[project]
name = "how-ai-mk-econ-great-again"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "openai>=1.106.1",
    "python-dotenv>=1.1.1",
]
